- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    python -m pip install -r requirements.txt
- name: Install OpenCV
  run: python -m pip install opencv-python-headless==4.9.0
