name: Text Recognition CI/CD

on:
  push:
    branches:
      - B-Prasanth3/text_recognition_/main

jobs:
  install-dependencies:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Install OpenCV
        run: python -m pip install opencv-python-headless==4.9.0

  run-tests:
    needs: install-dependencies
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Install OpenCV
        run: python -m pip install opencv-python-headless==4.9.0

      - name: Run tests
        run: python -m pytest

  deploy:
    needs: run-tests
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Install OpenCV
        run: python -m pip install opencv-python-headless==4.9.0

      - name: Deploy
        run: python deploy_script.py
